site: black-mountains
data_dir: /vol/v1/FCF/bayesUpdate/data
output_dir: /vol/v1/FCF/bayesUpdate/results
n.samples: 5000
n.threads: 50
max.dist: 5
max.effective.range: 100
min.effective.range: 0.001
spatial.variance.scale: 750
nugget.variance.scale: 750
starting.decay.rate: 1.5
starting.spatial.variance: 4000
starting.nugget.variance: 4000
decay.rate.tuning: 0.06
spatial.variance.tuning: 0.06
nugget.variance.tuning: 0.06
discard_offset: 60
chain_sample: 8
